ALTER TABLE AGILE_LIST ADD CONSTRAINT FK_AGILE_LIST_STORY_ID FOREIGN KEY (STORY_ID) REFERENCES STORY(KEY);
ALTER TABLE PROJECT ADD CONSTRAINT FK_PROJECT_BACKLOG_ID FOREIGN KEY (BACKLOG_ID) REFERENCES AGILE_LIST(KEY);
ALTER TABLE SPRINT ADD CONSTRAINT FK_SPRINT_BACKLOG_ID FOREIGN KEY (BACKLOG_ID) REFERENCES AGILE_LIST(KEY);
ALTER TABLE SPRINT ADD CONSTRAINT FK_SPRINT_DOING_ID FOREIGN KEY (DOING_ID) REFERENCES AGILE_LIST(KEY);
ALTER TABLE SPRINT ADD CONSTRAINT FK_SPRINT_DONE_ID FOREIGN KEY (DONE_ID) REFERENCES AGILE_LIST(KEY);
ALTER TABLE USER ADD CONSTRAINT FK_USER_PROJECT_ID FOREIGN KEY (PROJECT_ID) REFERENCES PROJECT(KEY);
ALTER TABLE USER ADD CONSTRAINT FK_USER_SPRINT_ID FOREIGN KEY (SPRINT_ID) REFERENCES SPRINT(KEY);

-- PROTECTED CODE -->
