
CREATE TABLE AGILE_LIST (
    STORY_ID           NUMBER(10) NOT NULL,
    TITLE              VARCHAR2(40),
    CONSTRAINT AGILE_LIST_PK PRIMARY KEY ( STORY_ID ));

CREATE SEQUENCE AGILE_LIST_SEQ;


CREATE TABLE PROJECT (
    KEY                NUMBER(10) NOT NULL,
    TITLE              VARCHAR2(100),
    DESCRIPTION        VARCHAR2(1000),
    BACKLOG_ID         NUMBER(10),
    START_DATE         DATE,
    END_DATE           DATE,
    CONSTRAINT PROJECT_PK PRIMARY KEY ( KEY ));

CREATE SEQUENCE PROJECT_SEQ;


CREATE TABLE SPRINT (
    BACKLOG_ID         NUMBER(10) NOT NULL,
    TITLE              VARCHAR2(200),
    DESCRIPTION        VARCHAR2(1000),
    DOING_ID           NUMBER(10) NOT NULL,
    DONE_ID            NUMBER(10) NOT NULL,
    START_DATE         DATE,
    END_DATE           DATE,
    CONSTRAINT SPRINT_PK PRIMARY KEY ( BACKLOG_ID, DOING_ID, DONE_ID ));

CREATE SEQUENCE SPRINT_SEQ;


CREATE TABLE STORY (
    KEY                NUMBER(10) NOT NULL,
    DESCRIPTION        VARCHAR2(500),
    ESTIMATED_HOURS    NUMBER(3),
    REMAINING_HOURS    NUMBER(3),
    PROJECT_ID         NUMBER(10),
    CONSTRAINT STORY_PK PRIMARY KEY ( KEY ));

CREATE SEQUENCE STORY_SEQ;


CREATE TABLE USER (
    KEY                NUMBER(10) NOT NULL,
    USERNAME           VARCHAR2(40),
    PASSWORD           VARCHAR2(200) NOT NULL,
    FIRST_NAME         VARCHAR2(40),
    LAST_NAME          VARCHAR2(40),
    EMAIL              VARCHAR2(40) NOT NULL,
    PROJECT_ID         NUMBER(10),
    SPRINT_ID          NUMBER(10),
    CONSTRAINT USER_PK PRIMARY KEY ( KEY ));

CREATE SEQUENCE USER_SEQ;

