DROP TABLE AGILE_LIST;
DROP SEQUENCE AGILE_LIST_SEQ;

DROP TABLE PROJECT;
DROP SEQUENCE PROJECT_SEQ;

DROP TABLE SPRINT;
DROP SEQUENCE SPRINT_SEQ;

DROP TABLE STORY;
DROP SEQUENCE STORY_SEQ;

DROP TABLE USER;
DROP SEQUENCE USER_SEQ;

ALTER TABLE AGILE_LIST DROP CONSTRAINT FK_AGILE_LIST_STORY_ID;
