-- Remove Original Table and Sequence

DROP TABLE AGILE_LIST;
DROP SEQUENCE AGILE_LIST_SEQ;
-- Create Table


CREATE TABLE AGILE_LIST (
    KEY                NUMBER(10) NOT NULL,
    TITLE              VARCHAR2(40),
    STORY_ID           NUMBER(10),
    CONSTRAINT AGILE_LIST_PK PRIMARY KEY ( KEY ));

CREATE SEQUENCE AGILE_LIST_SEQ;


-- Sample Select Statement

SELECT
    KEY, TITLE, STORY_ID 
from AGILE_LIST
WHERE
    KEY = 0;

-- PROTECTED CODE -->