-- Remove Original Table and Sequence

DROP TABLE SPRINT;
DROP SEQUENCE SPRINT_SEQ;
-- Create Table


CREATE TABLE SPRINT (
    BACKLOG_ID         NUMBER(10) NOT NULL,
    TITLE              VARCHAR2(200),
    DESCRIPTION        VARCHAR2(1000),
    DOING_ID           NUMBER(10) NOT NULL,
    DONE_ID            NUMBER(10) NOT NULL,
    START_DATE         DATE,
    END_DATE           DATE,
    CONSTRAINT SPRINT_PK PRIMARY KEY ( BACKLOG_ID, DOING_ID, DONE_ID ));

CREATE SEQUENCE SPRINT_SEQ;


-- Sample Select Statement

SELECT
    BACKLOG_ID, TITLE, DESCRIPTION, DOING_ID, DONE_ID, START_DATE, END_DATE 
from SPRINT
WHERE
    BACKLOG_ID = 0;

-- PROTECTED CODE -->