-- Remove Original Table and Sequence

DROP TABLE SPRINT;
DROP SEQUENCE SPRINT_SEQ;
-- Create Table


CREATE TABLE SPRINT (
    KEY                NUMBER(10) NOT NULL,
    TITLE              VARCHAR2(200),
    DESCRIPTION        VARCHAR2(1000),
    BACKLOG_ID         NUMBER(10),
    DOING_ID           NUMBER(10),
    DONE_ID            NUMBER(10),
    START_DATE         DATE,
    END_DATE           DATE,
    CONSTRAINT SPRINT_PK PRIMARY KEY ( KEY ));

CREATE SEQUENCE SPRINT_SEQ;


-- Sample Select Statement

SELECT
    KEY, TITLE, DESCRIPTION, BACKLOG_ID, DOING_ID, DONE_ID, START_DATE, END_DATE 
from SPRINT
WHERE
    KEY = 0;

-- PROTECTED CODE -->