-- Remove Original Table and Sequence

DROP TABLE STORY;
DROP SEQUENCE STORY_SEQ;
-- Create Table


CREATE TABLE STORY (
    KEY                NUMBER(10) NOT NULL,
    DESCRIPTION        VARCHAR2(500),
    ESTIMATED_HOURS    NUMBER(3),
    REMAINING_HOURS    NUMBER(3),
    PROJECT_ID         NUMBER(10),
    CONSTRAINT STORY_PK PRIMARY KEY ( KEY ));

CREATE SEQUENCE STORY_SEQ;


-- Sample Select Statement

SELECT
    KEY, DESCRIPTION, ESTIMATED_HOURS, REMAINING_HOURS, PROJECT_ID 
from STORY
WHERE
    KEY = 0;

-- PROTECTED CODE -->